### ISSUE TITLE
New Teams version V2

### ISSUE THREAD

**Issue by krlspj** [Bnz-0/fuk-u-teams#3]
Can you try to adapt to the new version of teams V2?

**Comment by Bnz-0** [comment]
Yup, I need it too. I'll try as soon as I have time

**Comment by Bnz-0** [comment]
Now should work also on v2 :tada:
The API are still the same of v1, but the script was not loading because of a new CSP introduced in the v2

**Comment by Bnz-0** [comment]
@krlspj sorry to bother you, did you try this new version on v2? Because today is not working for me and I fear that yesterday teams decided to switch back to v1 and I didn't notice :(

**Comment by Bnz-0** [comment]
Ok I finally did it. The solution is not compatible with teams 1.0, so I created the branch `teams-v1` to still have a working solution for that old version

**Comment by krlspj** [comment]
Thanks, it is working now! :)
